INC=/opt/X11/include
LIB=/opt/X11/lib
all:
	g++ lg.cpp -Ofast -std=c++11 -I $(INC) -L $(LIB) -lX11 -lGLU -lGL -lglut -lm -lpthread -lboost_program_options -o lg
	#g++ lg.cpp -Ofast -std=c++0x -I ~/acml/gfortran64/include/ -L ~/acml/gfortran64/lib/ -lX11 -lGLU -lGL -lglut -lm -lpthread -lacml -lboost_program_options -o lg
